export const LABELS = {
    WISHLIST: 'Wishlist',
    WISHLISTS: 'Wishlists',
    GIFTING: 'Gifting',
    WISHLIST_GIFTING: 'Wishlist & Gifting',
    MY_WISHLISTS: 'My Wishlists',
    ADD_TO_WISHLIST: 'Add to Wishlist',
    SAVE_TO_WISHLIST: 'Save to Wishlist',
    CREATE_NEW_WISHLIST: 'Create New Wishlist',
    WISHLIST_NAME: 'Wishlist Name',
    ADDED_TO_WISHLIST: 'Added to Wishlist',
    ALREADY_ADDED_TO_WISHLIST: 'Already Added to Wishlist',
    WISHLIST_EMPTY: 'Your wishlist is empty',
    SHARE_WISHLIST: 'Share Wishlist',
    FIND_WISHLIST: 'Find a Wishlist',
    SEARCH_WISHLISTS: 'Search Wishlists',
    WISHLIST_SETTINGS: 'Wishlist Settings',
    REMOVE_FROM_WISHLIST: 'Remove from Wishlist',
    WISHLIST_RECIPIENT: 'Wishlist Recipient',
    DELIVERY_PREFERENCE: 'Delivery Preference',
    SHARE_ADDRESS_WITH_GIFTERS: 'Share address with gifters',
    ADDRESS_HINT: 'Choose a saved address to make it visible on this wishlist.',
    ADDRESS_EMPTY_HINT: 'Please add a delivery address in your profile settings to enable address sharing.',
    MANAGE: 'Manage',
    DELIVERY_INSTRUCTIONS: 'Delivery instructions (optional)',
    CREATE_PRIVATE_LIST: 'Create Private List',
    SAVE_CHANGES: 'Save Changes',
    DELETE_LIST: 'Delete List',
    DELETE_CONFIRMATION: 'Are you sure? Items will be moved to your default list.',
    CANNOT_DELETE_DEFAULT: 'The default list cannot be deleted.',
    EDIT_LIST: 'Edit List',
    GIFT_CATEGORY: 'Gift Category',
    SPECIFY_OCCASION: 'Specify Occasion',
    CREATE_NEW_LIST: 'Create a new list',
};
